In [1]:
import pandas as pd

In [3]:
# dataframes using lists

data = [["Priyasha",99],["Neha",56]]

pd.DataFrame(data,columns=["Name","Marks"])

       Name  Marks
0  Priyasha     99
1      Neha     56

In [4]:
# dataframes using dictionaries
d = {'a':[1,2,3],'b':[10,20,40]}

In [6]:
pd.DataFrame(d)

   a   b
0  1  10
1  2  20
2  3  40

In [7]:
import numpy as np

In [9]:
# Dataframes using numpy

arr = np.array([[1,2,3],[4,5,6]])

In [16]:
df = pd.DataFrame(arr,columns=["1st","2nd","3rd"])
df

   1st  2nd  3rd
0    1    2    3
1    4    5    6

In [22]:
# Reading excel using pandas instead od loops or open file

df=pd.read_excel("data.xlsx")

In [23]:
df

     Name School  Marks
0   Priya    VPS     78
1   Rishu    WAS     88
2   Umang    WES     67
3    Yash    TPS     99
4    Ashi    GPS     45
5  Shubhu    POS     34
6   Pallu    JKS     64
7    Vasi    ERS     87
8   Dukhi    TRS     57

In [28]:
# Reading json file

df = pd.read_json("sample.json")

In [29]:
df

   name  occupation
0   PPP    Engineer
1  TTTT  Engineer 2

In [30]:
# Reading data from URL

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [31]:
# Exploring EDA

df.head()   # first 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [33]:
df.tail()   # last 5 rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [34]:
df.info()   # information about dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [35]:
df.describe()   # statistical terms

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [37]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [39]:
df.shape   # dimensions (rows X columns)

(244, 7)